name: usahaku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  age_calculator: ^1.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.7.2
  dynamic_fa_icons: ^1.0.0+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_datetime_picker_bdaya: ^2.0.0
  flutter_easyloading: ^3.0.3
  flutter_map: ^2.2.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  get: 4.6.5
  get_cli: ^1.8.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  http: ^0.13.4
  image_picker: ^0.8.5+3
  lottie: ^1.4.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
